//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baithi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chietkhau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chietkhau()
        {
            this.hdchitiets = new HashSet<hdchitiet>();
        }
    
        public int IDchietkhau { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> chietkhauphantram { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdchitiet> hdchitiets { get; set; }
    }
}
