//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baithi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdchitiet
    {
        public int IDhoadon { get; set; }
        public Nullable<int> IDsp { get; set; }
        public Nullable<int> IDkhachhang { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> dongia { get; set; }
        public Nullable<double> thanhtien { get; set; }
        public string tensp { get; set; }
        public Nullable<int> IDnv { get; set; }
        public Nullable<int> IDchietkhau { get; set; }
    
        public virtual chietkhau chietkhau { get; set; }
        public virtual nv nv { get; set; }
        public virtual sanpham sanpham { get; set; }
        public virtual hoadonsp hoadonsp { get; set; }
    }
}
