//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baithi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonsp
    {
        public int IDhoadon { get; set; }
        public Nullable<int> IDkhachhang { get; set; }
        public Nullable<System.DateTime> ngayban { get; set; }
        public Nullable<double> tongtien { get; set; }
    
        public virtual hdchitiet hdchitiet { get; set; }
        public virtual kh_hang kh_hang { get; set; }
    }
}
