//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baithi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.hdchitiets = new HashSet<hdchitiet>();
        }
    
        public int IDsp { get; set; }
        public string tensp { get; set; }
        public string size { get; set; }
        public string loai { get; set; }
        public string hang { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> giathanh { get; set; }
        public string anh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdchitiet> hdchitiets { get; set; }
        public virtual khosp khosp { get; set; }
        public virtual loai loai1 { get; set; }
        public virtual ncc ncc { get; set; }
    }
}
