//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtinmathang
    {
        public int mamh { get; set; }
        public string tenmh { get; set; }
        public string theloai { get; set; }
        public string nhacc { get; set; }
        public Nullable<int> giaban { get; set; }
        public Nullable<double> gianhap { get; set; }
        public Nullable<int> soluong { get; set; }
        public string url_image { get; set; }
    }
}
